fragment PostParts on Post {
  __typename
  title
  createdAt
  updatedAt
  description
  category
  tags
  draft
  image
  body
}

fragment MicroblogParts on Microblog {
  __typename
  title
  createdAt
  body
}
