fragment PostParts on Post {
  __typename
  title
  description
  category
  createdAt
  updatedAt
  image
  draft
  body
}

fragment MicroblogParts on Microblog {
  __typename
  title
  createdAt
  body
}
